name: "Generate icons"
description: "Generate icons and push it as an artifact"

inputs:
  upload_artifact:
    description: 'Upload artifact'
    default: 'true'

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Compiled icons
      shell: bash
      run: |
        GOPATH=$(go env GOPATH)
        export GOPATH
        go get github.com/cratonica/2goarray
        go install github.com/cratonica/2goarray
        ./generate-icons.sh
    - uses: actions/upload-artifact@v4
      if: ${{ inputs.upload_artifact == 'true' }}
      with:
        name: icons
        path: icons/*.go